version: "3"
services:
    ic-backend:
        container_name: ic-backend
        build:
            context: ../../
            dockerfile: Dockerfile
        volumes:
            - ../../:/var/www/html
            - ../php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www/html
        ports:
            - 2555:80
        networks:
            - ic-network
        restart: always

networks:
    ic-network:
        external: true
