version: "3"
services:
    backend:
        container_name: ic-backend
        build:
            context: ../../
            dockerfile: Dockerfile
        volumes:
            - ../../:/var/www/html
            - ../php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www/html
        ports:
            - 2555:80
            - 5173:5173
        networks:
            - ic-network
        restart: always

    frontend:
        image: nginx:latest
        container_name: ic-frontend
        ports:
            - "2556:80"
        volumes:
            - ./dist/sakai-ng:/usr/share/nginx/html:ro
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - ic-network
        restart: always

    test:
        image: nginx:latest
        container_name: ic-test
        ports:
            - "2557:80"
        networks:
            - ic-network
        restart: always

    proxy:
        image: nginx:latest
        container_name: proxy
        ports:
            - "2554:80"
        volumes:
            - ./pedraodev.shop.conf:/etc/nginx/conf.d/pedraodev.shop.conf:ro
            - ./pedraodev2.shop.conf:/etc/nginx/conf.d/pedraodev2.shop.conf:ro
        networks:
            - ic-network
        restart: always

networks:
    ic-network:
        driver: "bridge"
