version: "3"
services:
    backend:
        container_name: ic-backend
        build:
            context: ../../
            dockerfile: Dockerfile
        volumes:
            - ../../:/var/www/html
            - ../php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www/html
        ports:
            - 2555:80
            - 5173:5173
        networks:
            - ic-network

    frontend:
        image: nginx:latest
        container_name: ic-frontend
        ports:
            - "2556:80"
        volumes:
            - ./dist/sakai-ng:/usr/share/nginx/html:ro
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - ic-network

    proxy:
        image: nginx:latest
        container_name: proxy
        ports:
            - "2554:80"
        volumes:
            - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
        networks:
            - ic-network

networks:
    ic-network:
        driver: "bridge"
